name: assignment-test
on: [push]
jobs:
    unit-test:
        container: cuaesd/aesd-autotest:unit-test
        runs-on: ubuntu-22.04
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
    full-test:
        container: cuaesd/aesd-autotest:assignment3
        runs-on: ubuntu-22.04
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Install cross-compiler in container
            run: |
              apt-get update
              apt-get install -y gcc-aarch64-linux-gnu bc u-boot-tools flex bison libssl-dev libelf-dev sudo cpio
          - name: Run full test
            run: ./full-test.sh
